### ISSUE TITLE
BLEU score too low

### ISSUE THREAD

**Issue by LucaMontano** [OpenNMT/OpenNMT-tf#771] opened 2021-01-19 12:49 UTC
Good afternoon,
I'm using an Italian -> Friulian dataset to train OpenNMT-tf models. I've tried to use the auto configuration and the standard configuration file with the path to the datasets. After the training loops I've launched onmt-main with infer option. From the result of the command I've seen that running multi-bleu.perl on the target-predicted pair of sentences I received a BLEU score of 2.91 versus 20 of the last eval at the end of the last training loop. I think that can be overfitting over the predictions of the model. Is it right? What can I do to improve the BLEU score of the test predictions?

PS: I do 10000 training steps and evalution every 500 steps.

**Comment by guillaumekln** [comment] 2021-01-19 12:55
Hi,

How many training data are you using?

**Comment by LucaMontano** [comment] 2021-01-19 13:05
I'm using 20856 sentences as training dataset

**Comment by LucaMontano** [comment] 2021-01-19 13:28
I know it's a poor dataset, as described in the documentation. I don't need to have a lot of sentences at now. The only document I use is the Bible. I've used OpenNMT-py with RNN and Transformer as models before OpenNMT-tf. The lowest BLEU score I received for in-domain test with OpenNMT-py is 9.5

**Comment by guillaumekln** [comment] 2021-01-19 13:31
In general this is not enough data to train a NMT system, especially with the default auto configuration.

I would suggest you do some research around "low resource neural machine translation". Some papers have practical recommendations on how to train NMT systems with few training data.

**Comment by LucaMontano** [comment] 2021-01-19 13:38
I saw some research papers on that topic. Is there any type of optimization I can use to improve prediction scores?

**Comment by LucaMontano** [comment] 2021-01-19 13:50
I'm writing my bachelor thesis using that data because I don't have any other.

**Comment by guillaumekln** [comment] 2021-01-19 16:31
Unfortunately I don't have much experience with low resource training. First thing you can try is to train a smaller model such as `NMTSmallV1`. You can also find some ideas on the [forum](https://forum.opennmt.net/search?q=low%20resource).

Let me close this issue since it is not a bug. Feel free to open a topic on the forum to discuss this further.

**Closed by guillaumekln** 2021-01-19 16:31 UTC
