### ISSUE TITLE
OpenNMT SentencePiece tokenized output token not in the vocabulary.

### ISSUE THREAD

**Issue by FPBHW** [OpenNMT/OpenNMT-tf#841] opened 2021-06-24 14:11 UTC
Hi,

we have observed that files tokenized via OpenNMT (with sentencepiece) create tokenized files that contain tokens that are not in the .vocab file of the vocabulary. This *may* be related to the add_dummy_prefix option, as the non-existing tokens tend to start with an '_', (example _AB) and a vocabulary does seem to have the same token without the leading converted space ("AB").

Could anyone shed any light on this issue ?

Many thanks in advance!

**Comment by FPBHW** [comment] 2021-06-24 14:17
Note: all characters in the input are present in the vocabulary, so it could have been tokenized correctly.

**Comment by guillaumekln** [comment] 2021-06-24 14:26
Hi,

Yes, there was an issue where in some cases the tokenizer attached the spacer "_" to the token when it should not. It is already fixed in the latest version of the tokenizer:

```bash
pip install --upgrade pyonmttok
```

**Comment by guillaumekln** [comment] 2021-06-29 08:07
Closing since the issue is resolved.

**Closed by guillaumekln** 2021-06-29 08:07 UTC
Labels: bug

**Comment by FPBHW** [comment] 2021-06-29 09:34
Thank you, could you confirm which version includes this bugfix ?

**Comment by guillaumekln** [comment] 2021-06-29 09:57
The fix is included in `pyonmttok>=1.26.2` which is required by OpenNMT-tf 2.20 and above.
