### ISSUE TITLE
Bugs happen in the Inference step

### ISSUE THREAD

**Issue by Lawhy** [OpenNMT/OpenNMT-tf#167] opened 2018-07-08 18:14 UTC
Hi,
I am using the NMTBig model to train a set of English-Chinese data. The training process goes well but when I used the trained model to predict my development/test data, the following error comes out:
`InvalidArgumentError (see above for traceback): flat indices[814, :] = [5, 12, 6] does not index into param (shape: [7,30,5,10]).
         [[Node: seq2seq/decoder_1/decoder_1/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](seq2seq/decoder_1/decoder_1/Reshape_2, seq2seq/decoder_1/decoder_1/stack)]]
`
Do you have any clue why this is happening? 

Many thanks.

**Comment by Lawhy** [comment] 2018-07-08 19:36
The full error is:
`Caused by op u'seq2seq/decoder_1/decoder_1/GatherNd', defined at:
  File "/disk/ocean/lhe/en2chi/venv/bin/onmt-main", line 11, in <module>
    sys.exit(main())
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/opennmt/bin/main.py", line 147, in main
    log_time=args.log_prediction_time)
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/opennmt/runner.py", line 242, in infer
    hooks=infer_hooks):
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 496, in predict
    features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/opennmt/models/model.py", line 128, in _model_fn    _, predictions = self._build(features, labels, params, mode, config=config)
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/opennmt/models/sequence_to_sequence.py", line 185, in _build
    return_alignment_history=True))
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/opennmt/decoders/rnn_decoder.py", line 258, in dynamic_decode_and_search
    decoder, maximum_iterations=maximum_iterations)
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 314, in dynamic_decode
    final_outputs, final_state, final_sequence_lengths)
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py", line 458, in finalize
    final_state.cell_state))
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/tensorflow/python/util/nest.py", line 375, in map_structure
    structure[0], [func(*x) for x in entries])
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py", line 457, in <lambda>
    t, outputs.parent_ids, final_state.lengths),
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py", line 620, in _maybe_sort_array_beams
    return gather_tree_from_array(t, parent_ids, sequence_length)
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py", line 180, in gather_tree_from_array
    ordered = array_ops.gather_nd(gather_from, indices)
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2975, in gather_nd
    "GatherNd", params=params, indices=indices, name=name)
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/disk/ocean/lhe/en2chi/venv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): flat indices[814, :] = [5, 12, 6] does not index into param (shape: [7,30,5,10]).
         [[Node: seq2seq/decoder_1/decoder_1/GatherNd = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](seq2seq/decoder_1/decoder_1/Reshape_2, seq2seq/decoder_1/decoder_1/stack)]]`

**Comment by guillaumekln** [comment] 2018-07-09 07:34
Hello,

This is a duplicate of #142, please check this issue and the [current workaround](https://github.com/OpenNMT/OpenNMT-tf/issues/142#issuecomment-394279587).

As several people have already encountered this bug, I will try to reproduce it and submit a fix to TensorFlow.

**Closed** 2018-07-09 07:34 UTC
Labels: stat:duplicate, type:bug
