### ISSUE TITLE
Using CPU with 8 GPU detected by Tensorflow

### ISSUE THREAD

**Issue by FPBHW** [OpenNMT/OpenNMT-tf#847] opened 2021-07-01 07:15 UTC
Hi,

we encounter a problem where TensorFlow detects the GPU's, but OpenNMT doesn't use them. We upgraded to OpenNMT version v2.20.0 due to tokenization issues. Currently, we see:
```
2021-06-30 22:07:29.427086: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1

2021-06-30 22:07:29.427112: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10

2021-06-30 22:07:29.427123: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10

2021-06-30 22:07:29.427133: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10

2021-06-30 22:07:29.427143: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10

2021-06-30 22:07:29.427152: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10

2021-06-30 22:07:29.427162: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7

2021-06-30 22:07:29.450581: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1, 2, 3, 4, 5, 6, 7

2021-06-30 22:07:29.450625: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1

2021-06-30 22:07:34.768925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:

2021-06-30 22:07:34.768979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 1 2 3 4 5 6 7 

2021-06-30 22:07:34.768990: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N Y Y Y Y Y Y Y 

2021-06-30 22:07:34.768997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 1:   Y N Y Y Y Y Y Y 

2021-06-30 22:07:34.769003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 2:   Y Y N Y Y Y Y Y 

2021-06-30 22:07:34.769010: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 3:   Y Y Y N Y Y Y Y 

2021-06-30 22:07:34.769016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 4:   Y Y Y Y N Y Y Y 

2021-06-30 22:07:34.769023: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 5:   Y Y Y Y Y N Y Y 

2021-06-30 22:07:34.769029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 6:   Y Y Y Y Y Y N Y 

2021-06-30 22:07:34.769035: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 7:   Y Y Y Y Y Y Y N 

2021-06-30 22:07:34.784618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30120 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:2d:00.0, compute capability: 7.0)

2021-06-30 22:07:34.786520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 30120 MB memory) -> physical GPU (device: 1, name: Tesla V100-SXM2-32GB, pci bus id: 0000:32:00.0, compute capability: 7.0)

2021-06-30 22:07:34.788286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 30120 MB memory) -> physical GPU (device: 2, name: Tesla V100-SXM2-32GB, pci bus id: 0000:5b:00.0, compute capability: 7.0)

2021-06-30 22:07:34.790445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 30120 MB memory) -> physical GPU (device: 3, name: Tesla V100-SXM2-32GB, pci bus id: 0000:5f:00.0, compute capability: 7.0)

2021-06-30 22:07:34.792601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:4 with 30120 MB memory) -> physical GPU (device: 4, name: Tesla V100-SXM2-32GB, pci bus id: 0000:b5:00.0, compute capability: 7.0)

2021-06-30 22:07:34.794338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:5 with 30120 MB memory) -> physical GPU (device: 5, name: Tesla V100-SXM2-32GB, pci bus id: 0000:be:00.0, compute capability: 7.0)

2021-06-30 22:07:34.796542: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:6 with 30120 MB memory) -> physical GPU (device: 6, name: Tesla V100-SXM2-32GB, pci bus id: 0000:e1:00.0, compute capability: 7.0)

2021-06-30 22:07:34.798292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:7 with 30120 MB memory) -> physical GPU (device: 7, name: Tesla V100-SXM2-32GB, pci bus id: 0000:e9:00.0, compute capability: 7.0)

2021-06-30 22:07:34.807000: I main.py:326] Searching the largest batch size between 256 and 16384 with a precision of 256...

2021-06-30 22:07:34.812000: I main.py:326] Trying training with batch size 8320...

2021-06-30 22:07:36.669000: I main.py:326] ... failed.

2021-06-30 22:07:36.673000: I main.py:326] Trying training with batch size 4287...

2021-06-30 22:07:38.471000: I main.py:326] ... failed.

2021-06-30 22:07:38.476000: I main.py:326] Trying training with batch size 2271...

2021-06-30 22:07:40.358000: I main.py:326] ... failed.

2021-06-30 22:07:40.362000: I main.py:326] Trying training with batch size 1263...

2021-06-30 22:07:42.132000: I main.py:326] ... failed.

2021-06-30 22:07:42.137000: I main.py:326] Trying training with batch size 759...

2021-06-30 22:07:43.933000: I main.py:326] ... failed.

2021-06-30 22:07:43.938000: I main.py:326] Trying training with batch size 507...

2021-06-30 22:07:45.715000: I main.py:326] ... failed.

2021-06-30 22:07:45.715000: E main.py:326] Last training attempt exited with an error:

"""

Traceback (most recent call last):

  File "/root/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/root/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/bin/main.py", line 363, in <module>

    main()

  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/bin/main.py", line 326, in main

    hvd=hvd,

  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/runner.py", line 196, in train

    devices = misc.get_devices(count=num_devices, fallback_to_cpu=fallback_to_cpu)

  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/utils/misc.py", line 47, in get_devices

    "is" if len(devices) == 1 else "are",

ValueError: Requested 8 CPU devices but 1 CPU is visible

```

**Comment by FPBHW** [comment] 2021-07-01 07:22
Command line:
```
onmt-main --model_type TransformerBig --config ${TRAIN_CONFIG} --auto_config --mixed_precision train --with_eval --num_gpus 8
```

**Comment by FPBHW** [comment] 2021-07-01 07:23
We have tried both tensorflow 2.3 + cuda10.1 and TF 2.4 + CUDA 11

**Comment by FPBHW** [comment] 2021-07-01 07:31
Inference works fine with the same version, tokenization too.

**Comment by guillaumekln** [comment] 2021-07-01 07:47
Can you try to set a fixed batch size (!= 0) in the configuration and verify that the training is using the GPUs?

**Comment by FPBHW** [comment] 2021-07-01 08:08
Will do.

For comparison, here is the output from before the upgrade, it typically will end up larger than 10k:
```
NFO:tensorflow:Searching the largest batch size between 256 and 16384 with a precision of 256...
INFO:tensorflow:Trying training with batch size 8320...
INFO:tensorflow:... succeeded, continue until the search range is smaller than 256.
INFO:tensorflow:Trying training with batch size 12352...
INFO:tensorflow:... succeeded, continue until the search range is smaller than 256.
INFO:tensorflow:Trying training with batch size 14368...
INFO:tensorflow:... failed.
INFO:tensorflow:Trying training with batch size 13359...
INFO:tensorflow:... succeeded, continue until the search range is smaller than 256.
INFO:tensorflow:Trying training with batch size 13863...
INFO:tensorflow:... succeeded, continue until the search range is smaller than 256.
INFO:tensorflow:Trying training with batch size 14115...
INFO:tensorflow:... succeeded, continue until the search range is smaller than 256.
INFO:tensorflow:Batch size auto tuned to 12703.

```

**Comment by FPBHW** [comment] 2021-07-01 08:54
Training works just fine with v2,20.0 , tf 2.4.1 and cuda 11 using a fixed batch size of 4096

**Comment by guillaumekln** [comment] 2021-07-01 11:12
> ... side note: not sure how it got to a batch size of 12.7k if 14.1k was also succesful.

The memory usage can vary unexpectedly during the training. We prefer selecting a smaller batch size to prevent out of memory errors.

> Training works just fine with v2,20.0 , tf 2.4.1 and cuda 11 using a fixed batch size of 4096

So for some reasons the small training attempts to autotune the batch size (which run in a separate process) are not finding your GPUs.

From which OpenNMT-tf version are you upgrading?

**Comment by FPBHW** [comment] 2021-07-01 12:12
The previous version was 2.17.1

**Comment by guillaumekln** [comment] 2021-07-01 12:34
Thanks, this is helpful. I think I can see what the issue is and have a possible fix in the PR above.

I will shortly release a new version, but in the meantime the workarounds are:
* set a fixed batch size in the configuration
* rollback to version 2.17.1 (you can ensure that you have the latest tokenization fixes with `pip install --upgrade pyonmttok`)

**Comment by guillaumekln** [comment] 2021-07-01 14:13
The proposed fix is released in version 2.20.1. Can you verify?

**Comment by FPBHW** [comment] 2021-07-01 14:29
Yes, may take a moment ....

**Comment by FPBHW** [comment] 2021-07-01 14:59
Looks promising, still busy...
```
021-07-01 22:38:33.548000: I main.py:326] Searching the largest batch size between 256 and 16384 with a precision of 256...
2021-07-01 22:38:33.555000: I main.py:326] Trying training with batch size 8320...
2021-07-01 22:48:27.025000: I main.py:326] ... succeeded, continue until the search range is smaller than 256.
2021-07-01 22:48:27.934000: I main.py:326] Trying training with batch size 12352...
```

**Comment by FPBHW** [comment] 2021-07-02 07:47
Success!
```
2021-07-01 22:38:33.548000: I main.py:326] Searching the largest batch size between 256 and 16384 with a precision of 256...
2021-07-01 22:38:33.555000: I main.py:326] Trying training with batch size 8320...
2021-07-01 22:48:27.025000: I main.py:326] ... succeeded, continue until the search range is smaller than 256.
2021-07-01 22:48:27.934000: I main.py:326] Trying training with batch size 12352...
2021-07-01 22:58:26.367000: I main.py:326] ... succeeded, continue until the search range is smaller than 256.
2021-07-01 22:58:27.273000: I main.py:326] Trying training with batch size 14368...
2021-07-01 23:06:45.032000: I main.py:326] ... failed.
2021-07-01 23:06:45.039000: I main.py:326] Trying training with batch size 13359...
2021-07-01 23:16:40.742000: I main.py:326] ... succeeded, continue until the search range is smaller than 256.
2021-07-01 23:16:41.313000: I main.py:326] Trying training with batch size 13863...
2021-07-01 23:26:17.811000: I main.py:326] ... succeeded, continue until the search range is smaller than 256.
2021-07-01 23:26:18.246000: I main.py:326] Trying training with batch size 14115...
2021-07-01 23:35:49.690000: I main.py:326] ... succeeded, continue until the search range is smaller than 256.
2021-07-01 23:35:50.135000: I main.py:326] Batch size auto tuned to 9880.
```

**Comment by guillaumekln** [comment] 2021-07-02 07:51
Thanks for checking! We can close this issue.

**Closed by guillaumekln** 2021-07-02 07:51 UTC
Labels: bug

**Comment by FPBHW** [comment] 2021-07-02 10:36
Thank you for the very rapid follow-up and fix - much appreciated!
