### ISSUE TITLE
Running on CPU giving error after running local_init_op

### ISSUE THREAD

**Issue by mohammedayub44** [OpenNMT/OpenNMT-tf#231] opened 2018-10-16 15:20 UTC
Hi,

I'm running the quick start example from documentation on a CPU machine using the following - 
Tensorflow: 1.8.0
OS: Windows 
Python: 3.5.5

I get an error what seems to be a InvalidArgumentError while its trying to export the model. Attached is the cmd output log for more info. Also the config file. Not sure what I'm doing wrong. 

Command : `onmt-main train_and_eval --model_type NMTSmall --auto_config --config data.yml`
[error_opennmt_run_cpu.txt](https://github.com/OpenNMT/OpenNMT-tf/files/2483746/error_opennmt_run_cpu.txt)

[params_yml.zip](https://github.com/OpenNMT/OpenNMT-tf/files/2483752/params_yml.zip)

Appreciate any help.

Thanks !

Mohammed Ayub

**Comment by guillaumekln** [comment] 2018-10-16 15:32
Hi,

This is a duplicate of #142.

It was a TensorFlow issue that has been fixed in TensorFlow 1.10.0. If you can't update your TensorFlow version right now, you should replace `train_and_eval` by `train` to avoid the error.

**Comment by guillaumekln** [comment] 2018-10-16 18:46
Yes, you can still run `eval` or `infer` separately.

**Comment by mohammedayub44** [comment] 2018-10-16 18:55
great thanks @guillaumekln

**Comment by mohammedayub44** [comment] 2018-10-16 19:29
@guillaumekln 
Running the eval step gives the same error, not sure if any changes are required to the `.yml` file.
Below are the commands I ran without chaging anything in yml file: 
1) `onmt-main train --model_type NMTSmall --auto_config --config data.yml`
2) `onmt-main eval --model_type NMTSmall --auto_config --config data.yml`

Mohammed Ayub

**Comment by guillaumekln** [comment] 2018-10-16 19:50
Per #142, the issue happens during evaluation or inference (more specifically during beam search). Splitting training and evaluation only allows to run the training fully.

However, it only happens with small models or models that are not fully trained. I suggest letting the train run longer.

**Comment by mohammedayub44** [comment] 2018-10-17 01:16
@guillaumekln oh okay. I will try running it for longer time and update you. Thanks

**Comment by mohammedayub44** [comment] 2018-10-24 13:42
Sorry for the late response. I ran the model for about 12,000 steps and ran the eval its giving me the below error. 
**"OutOfRangeError: End of Sequence Error"**
Attached is the complete Command line output file.: 
[error_transformerbig.txt](https://github.com/OpenNMT/OpenNMT-tf/files/2510704/error_transformerbig.txt)

Is this because of short sentences in the eval file. I could see some of them have just one or 2 words in each line.

Thanks !
Mohammed Ayub

**Comment by guillaumekln** [comment] 2018-10-26 07:59
You should post a new issue with this error if it is still happening. I did not manage to reproduce it.

Closing this issue as it is initially a duplicate of #142.

**Closed by guillaumekln** 2018-10-26 07:59 UTC
Labels: stat:duplicate, type:bug
