### ISSUE TITLE
On Quickstart Example: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 0

### ISSUE THREAD

**Issue by duvallj** [OpenNMT/OpenNMT-tf#886] opened 2021-10-03 02:15 UTC
Hello,

I was trying to run a quick training example with this library, but following the quickstart instructions did not work. I didn't see another open issue like this so I'm filing one.

| | |
| :-- | :-- |
| **Operating System** | Windows 10 21H1 |
| **Python Version** | Python 3.8.7 |
| **OpenNMT Version** | OpenNMT 2.22.0 (installed via pip) |
| **Tensorflow Version** | Tensorflow 2.6.0 |
| **CUDA Version** | CUDA 11.1 |
| **CuDNN Version** | CuDNN 8.1.1 |

The rest of the packages installed in my environment can be found at [this gist](https://gist.github.com/duvallj/e8c79ad71fcae5fb5f7db8b3ae421178).

## Exact Commands Run

These are the same as the commands currently listed in [the Quickstart section of the documentation](https://opennmt.net/OpenNMT-tf/quickstart.html). All these commands were run in Windows CMD:
```
python -m venv venv
venv\Scripts\activate
pip install tensorflow
pip install OpenNMT-tf
wget https://s3.amazonaws.com/opennmt-trainingdata/toy-ende.tar.gz
tar xf toy-ende.tar.gz
cd toy-ende
onmt-build-vocab --size 50000 --save_vocab src-vocab.txt src-train.txt
onmt-build-vocab --size 50000 --save_vocab tgt-vocab.txt tgt-train.txt
echo model_dir: run/ > data.yml
echo data: >> data.yml
echo   train_features_file: src-train.txt >> data.yml
echo   train_labels_file: tgt-train.txt >> data.yml
echo   eval_features_file: src-val.txt >> data.yml
echo   eval_labels_file: tgt-val.txt >> data.yml
echo   source_vocabulary: src-vocab.txt >> data.yml
echo   target_vocabulary: tgt-vocab.txt >> data.yml
onmt-main --model_type Transformer --config data.yml --auto_config train --with_eval
```

This gives the following error ([full traceback in gist](https://gist.github.com/duvallj/862de61108806f55a6db0fdf607a9280)):
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 0: unexpected end of data


         [[node PyFunc_1 (defined at d:\documents\project_workspace\venv\lib\site-packages\opennmt\training.py:721) ]]
         [[gradients/global_norm/write_summary/summary_cond/then/_267/gradients/global_norm/write_summary/_59]]
0 successful operations.
0 derived errors ignored. [Op:__inference__forward_32442]

Errors may have originated from an input operation.
Input Source operations connected to node PyFunc_1:
 GatherNd_1 (defined at d:\documents\project_workspace\venv\lib\site-packages\opennmt\inputters\text_inputter.py:384)
 Sum_5 (defined at d:\documents\project_workspace\venv\lib\site-packages\opennmt\training.py:716)
```

## Attempts at fixing

Because this was a `UnicodeDecodeError`, I searched for the character `ord(0xc3) == 'Ã'` in the training data, and replaced all of the occurrences with a regular `'A'`. However, doing this and re-building the vocab tables did not make the error go away. I'm not familiar with the codebase and not sure where this could be happening, the error message isn't clear either.

Any help fixing this would be appreciated, as it's a bit of a bummer to run into an issue doing the quickstart.

**Comment by guillaumekln** [comment] 2021-10-05 14:39
Hi,

This looks like an encoding issue specific to Windows since I can't reproduce the error when running the quickstart on Ubuntu.

Do you have some experience with Python and TensorFlow? If yes, would you like to contribute a fix?

**Comment by duvallj** [comment] 2021-10-10 01:17
@guillaumekln I do have some experience with Python and Tensorflow, so I attempted to poke around the codebase to get a fix. Unfortunately, it seems like this is a Tensorflow error: https://github.com/tensorflow/tensorflow/issues/47022

This is because the default tokenizer uses `tf.strings.split` (https://github.com/OpenNMT/OpenNMT-tf/blob/0f1ee149d9a84a4af1b6422569f7647328211634/opennmt/tokenizers/tokenizer.py#L393), which has this error on Windows about not handling unicode characters correctly and truncating them at invalid boundaries.

Once a note in documentation is made to reference this limitation, I think we can close this issue.

**Comment by guillaumekln** [comment] 2021-10-11 08:53
Thanks for looking into this!

Can you try if this suggestion works for you? https://github.com/tensorflow/tensorflow/issues/43559#issuecomment-886728179

**Comment by duvallj** [comment] 2021-10-16 20:42
That does work! Very interesting and I'm not entirely sure why, but I'll take it

**Comment by guillaumekln** [comment] 2021-11-03 09:58
Great, I will close this issue since a workaround exists and it seems the actual bug is in TensorFlow.

**Closed by guillaumekln** 2021-11-03 09:58 UTC
Labels: bug
